### ISSUE TITLE
Whether we should disable these three windows on the dialog when we are not in edit mode？

### ISSUE THREAD

**Issue by dbxmm** [jovibor/HexCtrl#1]
IDC_HEXCTRL_SEARCH_EDIT_REPLACE
IDC_HEXCTRL_SEARCH_BUTTON_REPLACE
IDC_HEXCTRL_SEARCH_BUTTON_REPLACE_ALL

**Comment by jovibor** [comment]
Yes, you're right. Just overlooked.
Will fix.

**Comment by jovibor** [comment]
I pushed all the changes, you can check it out.
Thanks for reporting.
