### ISSUE TITLE
Minor memory leak

### ISSUE THREAD

**Issue by datasynergyuk** [jovibor/HexCtrl#10]
There are two potential issues with the new call to StringFromIID(). Suggest initialise pointer before call with LPWSTR lpwstr=nullptr and then free memory afterwards with CoTaskMemFree() to avoid memory leak. See: https://docs.microsoft.com/en-gb/windows/win32/api/combaseapi/nf-combaseapi-stringfromiid

NB: The reason this code used sprintf() originally was that it came from a codebase which could not assume COM had been initialised. Can you always assume that CoInitialize() etc has been called in every app that uses HexCtrl?

**Comment by jovibor** [comment]
> There are two potential issues with the new call to StringFromIID(). Suggest initialise pointer before call with LPWSTR lpwstr=nullptr and then free memory afterwards with CoTaskMemFree() to avoid memory leak. See: https://docs.microsoft.com/en-gb/windows/win32/api/combaseapi/nf-combaseapi-stringfromiid

I've overlooked this `CoTaskMemFree` part. I think i will revert it back to `swprint_f`.

> NB: The reason this code used sprintf() originally was that it came from a codebase which could not assume COM had been initialised. Can you always assume that CoInitialize() etc has been called in every app that uses HexCtrl?

Hmm...
I'm not exactly sure that `CoInitialize()` is strictly required for this function.
It's not get called in the current HexCtrl project even once, explicitly at least.
Maybe it's only mandatory for the `Co...` prefixed group of functions? Not sure...

**Comment by datasynergyuk** [comment]
I agree StringFromIID() seems to work without explicit COM init. However, MSDN  says "You need to initialize the COM library on a thread before you call any of the library functions except CoGetMalloc()". I think this is why the original code used simple sprintf because it avoided this ambiguity.
