### ISSUE TITLE
Suggestion: Update next/previous bookmark index when jumping to bookmark

### ISSUE THREAD

**Issue by datasynergyuk** [jovibor/HexCtrl#11]
Please can I suggest updating the current bookmark index (m_iCurrent) when the bookmark manager is used to jump to a specific bookmark (CHexBookmarks::GoBookmark). This will make subsequent next/previous bookmark behaviour more consistent.

**Comment by jovibor** [comment]
Yes, good catch.
I've also disposed of `IHexBkmVirtual::GetNext/GetPrev/Remove` methods. I think all next/prev logic can be handled by the control now.
