### ISSUE TITLE
Suggestion: Open bookmark manager with the current bookmark highlighted in list control

### ISSUE THREAD

**Issue by datasynergyuk** [jovibor/HexCtrl#12]
The user interface could be improved by opening the bookmark manager (by default) with the current bookmark selected. Now the current bookmark is tracked internally, this should work for both standard and virtual bookmarks.

**Comment by jovibor** [comment]
I mean, why?...
Bookmark manager is just an interface to the bookmarks, nothing more. It's not some primary feature. User can make use of bookmarks without it absolutely fine.

Moreover, it will immediately overlap main screen, irritating the user (me for sure).
It's like when you open a web site and accidentally background music, you didn't order, starts to play.

**Comment by datasynergyuk** [comment]
I think maybe you misunderstood my suggestion. I was suggesting that the bookmark manager listview scroll to the current bookmark so that it was visible by default. I was not suggesting that it change the current HexCtrl position or selection.

**Comment by jovibor** [comment]
> I was suggesting that the bookmark manager listview scroll to the current bookmark so that it was visible by default.

That's now more clear, when you're mentioning listview. 

Ok, i will make it.

**Comment by datasynergyuk** [comment]
Thank you.
