### ISSUE TITLE
[Suggestion] Ability to change code-page for the text area.

### ISSUE THREAD

**Issue by datasynergyuk** [jovibor/HexCtrl#16]
Many hex editor applications provide support for non-ANSI code pages. 

This can be useful for working with legacy data or data that was originally authored in a different language or character set such as EBCDIC. Currently, HexCtrl masks treats all text as "ASCII" and masks out text interpretation of characters <32 and > 127. This means the text interpretation is less useful for non-English languages (like French, German and Russian) that use accented or special characters > 127 and even less useful for languages such as  Chinese or Korean that typically use Unicode. 

It would be fantastic if HexCtrl supported code pages and Unicode text directly. This is not a feature that can easily be added in a parent application because the text conversion occurs directly inside HexCtrl. I would suggest that this work may not be all that difficult because Windows already has the MultiByteToWideChar() function for such conversions. For efficiency, it may be possible to convert one line (e.g. 16 bytes) of data at a time.

I would suggest there are two distinct scenarios to consider:

1. Different code pages - e.g. 7/8 bit characters that were represented using differently in original form. There is a list of OS supported code pages here: https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers

2. Unicode text - Text that was originally stored using fixed size 16-bit characters

My proposal leaves open the question of UTF-8 and other variable sized characters. MultiByteToWideChar()  does support this but the interpretation may depend on previous / next bytes and I imagine this could be more complex to implement.

**Comment by jovibor** [comment]
Supporting different 8bit code-pages seems more or less viable.
On the other hand, correct supporting of UTF-8 and stuff, when different code-points might consist of different amount of code-units, and you don't know a starting point..., might be very tricky. Things like ICU is here for reason.

I'm not sure yet, is it a good idea to add this kind of stuff in the control itself, or better to implement API to expose this burden to the parent app.
In the both cases it will require a redesigning of the control's internals, so will have to measure all pros and cons.

**Comment by datasynergyuk** [comment]
I agree. It is ironic that support for 8-bit code-pages seems quite straightforward but this is mainly for historic data. Modern data is typically UTF-8 and this is more complex because each code unit is variable length. I have done some more research and would suggest the following considerations:

1. 8-bit code pages - There is a one-to-one relationship between the binary data (each hex byte) and a character. The character displayed is simply an interpretation of that byte which can be retrieved using MultiByteToWideChar(). The one-to-one relationship means that such data can still be editable because a change in the displayed text leads to an unambiguous change in the binary data. In other words - the text can be editable. 

2. 16-bit characters (e.g. Windows UCS-2) - As above there is a one-to-one relationship between each pair of bytes and the displayed character. The text could therefore be editable. A significant wrinkle however is that interpretation depends on which byte the viewer considers the data starts on and staring just one byte later will result in a completely different visible display.  This means that a complete implementation of this feature requires an "offset by 1" flag. This would significantly complicate in-place editing?

NB:  I tried this on another leading hex editor and indeed the displayed text is completely different if the data starts one byte later. This is unsurprising since UCS-2 is not self synchronising. It seems to be widely assumed that UCS-2 data will always start on an even address offset but there really is no requirement for this in a binary file format. In other words, the ability to successfully view and search UCS-2 text completely depends on which address you start at (or having a BOM). 

3. Variable length characters (UTF-8, UTF-16) - These are self synchronising by design. It is therefore possible to identify valid UTF-8 data and ignore invalid data. However, the variable length encoding means there is no one-to-one relationship between the binary data and the displayed text. I would argue, this would make in-place editing impossible to implement unless the editor could delete/insert data and change the length of the underlying file. This is well beyond the scope of HexCtrl. Frustratingly, much modern data will be UTF-8 so this is probably the most useful case going forward. 

I think that covers everything. I hope I didn't misunderstand anything. In summary:

1. 8-bit fixed length encodings should be quite trivial because there is a Windows API to convert them to UCS-2 for display. In-place editing is possible because there is a one-to-one relationship between the data and characters.  This feature would principally be useful for viewing data created in legacy systems. I would suggest HexCtrl support such "code pages". Score: Easy.

2. 16-bit fixed length encoding - As above EXCEPT interpretation depends on the starting address. Other editors seem to assume this is always even. If this is the case, then in-place editing is possible as above (each 16 hex bytes convert to 8 characters). I would suggest "HexCtrl" support this.

A wrinkle is that  data can start on odd addresses too and this completely changes the interpretation. I would encourage HexCtrl to support display of such data (with an offset by one flag) but recognise that it would be very complicated to implement in-place editing. In this case, I would suggest the text area becomes read-only.  Score: Possible but complicated.

3. Variable length encoding - It seems impractical to support in-place editing because this would require data to be inserted/deleted. I would suggest the text area is always read-only in this case.

Beware: Apparently, MultiByteToWideChar() is not very tollerant of malformed UTF-8 text and will refuse to convert anything if the data appears invalid. This isn't unreasonable but is a complication because the code units can be 1-4 bytes in length. Other examples I have seen resolve this by parsing the UTF-8 themselves (either completely or to strip the invalid leading data). Again, a "full" solution would allow the starting address to be offset by 1-4 bytes. I don't even want to think about the implications of this! Score: Really difficult. 

I know you like a challenge!

**Comment by jovibor** [comment]
Having taken a look at few different hex editors i can conclude:
They all use different approaches in `UTF-8` mode viewing case. Mostly, substituting extra code-units with spaces. Correct string display is also often depending on data layout's starting position.
All in all: There is no *common/standard* approach to this matter.

I wouldn't be so glad to add too complicated logic to the control, to handle all this *variable length* mess.
So, for the start, `8-bit ASCII` code pages will be supported.
`UTF-8` and stuff will stay on hold for a while.

**Comment by datasynergyuk** [comment]
I agree and think that 8-bit code page support is an excellent step forward. The other more complex cases will have to wait for another day. Frustratingly, there doesn't seem to be Win32 API to get a list of available code pages (that I can find). Instead, you must create an array with the list of common code pages/names (see: https://docs.microsoft.com/en-gb/windows/win32/intl/code-page-identifiers) and then use GetCPInfo() to determine if they are actually available.

**Comment by jovibor** [comment]
Closed with 1c43771.
