### ISSUE TITLE
[Feature] Keyboard shortcut to jump over relative offsets.

### ISSUE THREAD

**Issue by datasynergyuk** [jovibor/HexCtrl#24]
1. Disable Go button if no / invalid address present
2. Support Ctrl+Left Arrow and Ctrol+Right Arrow for forward / backwards last relative address (allows you to jump through document in increments)

**Comment by jovibor** [comment]
1. Personally i don't like that much this kind of UI design in general, with input guessing.
2. I don't get it. `Ctrl+Arrow` in dialog input field?

**Comment by datasynergyuk** [comment]
1. This type of feature can be a big assistance to users (especially less skilled users) because it makes it validates input as they type rather than displaying an error message on completion. It isn't necessary for core function but makes a more polished UI. 

NB: It is the visual equivalent of the polish that frequently happens in the source code. Some of the changes don't alter functionality at all but modernise the code, make it more consistent and easier to follow. This is the UI equivalent.

2. The Ctrl+Arrow would not be in the input field but in the main hex control. If the user has previously used a relative jump, Ctrl+Arrow would repeat that jump. This would allow the user to navigate forwards / backwards through the data in steps. Please see the same feature which is already present in the private wrapper application.

**Comment by jovibor** [comment]
> 1. This would allow the user to navigate forwards / backwards through the data in steps.

I truly believe this is what bookmarks is for. Don't see a reason to duplicate this functionality.

**Comment by datasynergyuk** [comment]
How can a user use the bookmark feature to step through the data at specific increments?

**Comment by jovibor** [comment]
Now i see what you mean.
Actually, it can easily be done outside of the HexControl, but i can put it to my todo list.

**Comment by datasynergyuk** [comment]
Please would it be possible to have a HexCtrl method to check if relative jumps are currently available (so UI buttons can be enabled / disabled)?
