### ISSUE TITLE
CHexCtrl::SetSelection() doesn't scroll target into view

### ISSUE THREAD

**Issue by datasynergyuk** [jovibor/HexCtrl#5]
The current implementation of CHexCtrl::SetSelection() calls SetSelection() with scroll disabled. This means that when the selection is distant (not currently visible) nothing appears to happen. I tried adding an extra parameter to enable scroll and pass this down to SetSelection(). However, this didn't work.

Please can I suggest there is an option to bring the new selection into view. Maybe the solution would be to add SetCaretPos() to IHexCtrl?

**Comment by jovibor** [comment]
What's wrong with [`GoToOffset`](https://github.com/jovibor/HexCtrl#gotooffset) method?

`SetSelection` is meant to do what its name tells - to set a selection, which might be way more in size than the view size. Where do you suppose to scroll then? Beginning? Middle? End?

**Comment by datasynergyuk** [comment]
As ever, you are correct! Thank you.
