### ISSUE TITLE
Text display broken

### ISSUE THREAD

**Issue by fungshen85** [jovibor/HexCtrl#84]
Some text flow past the line. How can I fix.

![k](https://user-images.githubusercontent.com/77985659/208948319-525f0254-9f43-48f7-bcc4-821bb2c5a513.gif)

**Comment by jovibor** [comment]
It's not a bug, these code-pages just are not fully supported, its' stated in the title:
![image](https://user-images.githubusercontent.com/5625787/209026646-f539d501-caff-4f8b-a094-9e2eceacc1d7.png)

Multi-byte code-pages are tricky beasts, and not in priority atm.

**Comment by fungshen85** [comment]
Please when Korean text support?
