### ISSUE TITLE
Sometimes data is left out

### ISSUE THREAD

**Issue by ZhiyuanYuanNJ** [jovibor/HexCtrl#90]
Hi，
     I use GetDataSize() in my program to get the data length , GetData() to get the data and write to the file, but I find that sometimes the last byte is missed.
![hexctrl_BUG](https://github.com/jovibor/HexCtrl/assets/78026992/23399695-a45b-424c-8ca4-bd28759b9b7f)

**Comment by ZhiyuanYuanNJ** [comment]
By the way, if the last byte is FF, it is not lost, strange

**Comment by jovibor** [comment]
Have you solved the issue? Because I can't reproduce.

**Comment by ZhiyuanYuanNJ** [comment]
Sorry, this is not a BUG. The reason is that the uedit.exe failed to display complete data.
