### ISSUE TITLE
AVX2 feature detection

### ISSUE THREAD

**Issue by dmex** [jovibor/HexCtrl#93]
The CRT has feature detection for AVX before calling winmain and this code duplicates the CRT:

https://github.com/jovibor/HexCtrl/blob/1bbfffaf760792a4c903d472906fe7d2ab301336/HexCtrl/src/HexUtility.ixx#L143-L154

You can include the isa_availability header and just check the flags:  
```
#include <isa_availability.h>

extern int __isa_available;
#define ISA_AVAILABLE_X86 0
#define ISA_AVAILABLE_SSE2 1
#define ISA_AVAILABLE_SSE42 2
#define ISA_AVAILABLE_AVX 3
#define ISA_AVAILABLE_ENFSTRG 4
#define ISA_AVAILABLE_AVX2 5
#define ISA_AVAILABLE_AVX512 6

extern long __isa_enabled;
#define ISA_ENABLED_X86 0x00000001
#define ISA_ENABLED_SSE2 0x00000002
#define ISA_ENABLED_SSE42 0x00000004
#define ISA_ENABLED_AVX 0x00000008
#define ISA_ENABLED_ENFSTRG 0x00000010
#define ISA_ENABLED_AVX2 0x00000020
#define ISA_ENABLED_AVX512 0x00000040
```

Example usage (from the STL: https://github.com/microsoft/STL/blob/main/stl/src/vector_algorithms.cpp)
```
bool _Use_avx2() noexcept {
    return __isa_enabled & (1 << __ISA_AVAILABLE_AVX2);
}
```

**Comment by jovibor** [comment]
Well, you're absolutely right.
Except that this header is not standard compliant, and may be a subject to change in the future, see [here](https://developercommunity.visualstudio.com/t/C-header--exposes-non-standard-name-IS/10357533?space=8&q=80-bit+floating).
Also, this header was replaced in the STL internal usages recently by the `<__msvc_bit_utils.hpp>` helper header, see [here](https://github.com/microsoft/STL/issues/3692) and [here](https://github.com/microsoft/STL/pull/3721). 
Also, it's one more additional dependency, which I would rather avoid.
And eventually, it's just a matter of preference.
